apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 50 
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: {{.Release.Name}}-hypernode
        image: liveai.azurecr.io/hypernode:1.0.828-amd64
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 14580
        resources:
          requests:
            memory: "50Mi"
            cpu: "125m"
      - name: {{.Release.Name}}-mongodb
        image: mongo:3.6.20-xenial
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "50Mi"
            cpu: "125m"

