apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-hypernode-test
  namespace: arc-node
spec:
  releaseName: arc-node
  chart:
    git: https://github.com/nilslahrms/arc-node-demo
    ref: master
    path: charts/azure-arc-sample
  values:
    serviceName: arc-node

